<?xml version = "1.0" encoding="UTF-8"?>
<xsd:schema name="MODELO_CONCEPTUAL_BD_SICOZ.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MOVIMIENTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MOV_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BODEGAORIGEN".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BODEGADESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TIPOMOVIMIENTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "LIBROCONTABLE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ACTUALIZA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ITEMS".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.BODEGA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_MANZANA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_SITIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_TIPO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_CONTRATODEPOSITO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_FECHDEPOSITO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_UBICACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BOD_ESTADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BODEGA_STOCK".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.MAESTRO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "BODEGA_DESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.SOLICITUD_PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ABASTECE_PRODUCTOS".$value;?>" title=""  placeholder=".." class="form-control" type="ING.INGRESO_DET" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.DET_SOLICITUD_COMPRA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_DETALLE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_CANT".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_UMEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_OBS_UTILIDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_PORVENDER".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_ESTADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_USUARIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLC_USGESTOR".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF.RECINTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "REC_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "REC_RECINTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "EMP.CENTRO_COSTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CCOSTO_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CCOSTO_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CCOSTO_ENCARGADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.NOTA_CREDITO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "NCRED_ESTADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "NCRED_FECHA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.INGRESO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_NUMERODOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_TIPODOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_CORRELATIVO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_FECHADOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_FECHAVISACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_NUMEROVISACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_MONEDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_TIPODECAMBIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_IVA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_CIFTOTAL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_COSTOTOTAL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_VIUTOTAL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_ESTADO_PAGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_ESTADO_DOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_NETO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_TOTAL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_TIPODOCSVE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_BODEGA_REC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_PROD".$value;?>" title=""  placeholder=".." class="form-control" type="ING.INGRESO_DET" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ASOC_INGRESO".$value;?>" title=""  placeholder=".." class="form-control" type="ING.INGRESO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_27".$value;?>" title=""  placeholder=".." class="form-control" type="ING.NOTA_CREDITO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_18".$value;?>" title=""  placeholder=".." class="form-control" type="ING.OC" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.INGRESO_DET">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_ITEM".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_BODEGA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_ZETA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_CANTIDAD1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_CANTIDAD2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_VALOR1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_VALOR2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_ESTADO_INGRESO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SALIDAS_CAB">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_TIPODOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_NUMERODOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_FECHADOC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_BODEGAORIGEN".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_BODEGADESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_TIPODOCUMENTOSVE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_FECHAVISACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_NUMEROVISACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_CLIENTE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_MONEDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_TIPODECAMBIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_IVA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_VALOR1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_VALOR2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_NUMEROPEDIDO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_VENDEDOR".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_ACTUALIZA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_FORMADEPAGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_DESTINODEMERCANCIA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_AVANZADADESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_PAISDESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_ZONAFRANCADESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_REGIONDESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_RESOLUCIONSII".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_NUMRESOLUCIONSII".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_VALORUTM".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_PLAZOPRESENTACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SALIDAS_DET">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_TIPODOCUMENTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_NUMERODOCUMENTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_ITEM".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_TIPODOCSVE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_FECHAVISACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_NUMEROVISACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_ZETA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_BODEGAORIGEN".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_BODEGADESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_CANTIDAD1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_CANTIDAD2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_VALOR1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SAL_VALOR2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.SOLICITUD_COMPRA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_FECHA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_DESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_OBSERVACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_USUARIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_ESTADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLC_TIPO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "GENERA_SOLICITUD".$value;?>" title=""  placeholder=".." class="form-control" type="EMP.DEPARTAMENTO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_23".$value;?>" title=""  placeholder=".." class="form-control" type="ING.OC" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SOLICITUD_ITEM".$value;?>" title=""  placeholder=".." class="form-control" type="ING.DET_SOLICITUD_COMPRA" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_DET_NC_INGRESO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DNC_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.MAESTRO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MAE_SALDO_DISPONIBLE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MAE_SALDO_FISICO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MAE_SALDO_CRITICO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MAE_COSTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MAE_PRECIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MAE_DESC_PRECIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.ZETA">
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_ZETA1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_FECHAINGRESO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_CANTIDADINGRESADA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_UMEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:int"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_UNIDADESPORMEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_CIF".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_COSTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_COSTOINTERNO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_VIU".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_IMPUESTO1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_IMPUESTO2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
    <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZT_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   </xsd:element>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.PRODUCTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_CODIGOBARRA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_TIPO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_INFORMACIONADIC".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_CODIGOARANCELARIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_PRECIO1".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_PRECIO2".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_LEY18211".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_FABRICADOZF".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_MODELO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_MEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_MEDIDA_CTROL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_COLOR".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_PESO_CTROL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_VALOR_MEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.PRODUCTO_PROVEEDOR".$value;?>" title=""  placeholder=".." class="form-control" type="ING.PROVEEDOR" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "EQUIVALENCIA_PRODUCTO".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.EQUIVALENCIA_UNIDAD"  maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MATERIAS_PRIMA".$value;?>" title=""  placeholder=".." class="form-control" type="PROD.COMPUESTO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "REGISTRA_PRODUCTO".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.MAESTRO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.EQUIVALENCIA_UNIDAD">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_EQUIV_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_EQUIV_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD_EQUIV_UNIDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_MED_PROD".$value;?>" title=""  placeholder=".." class="form-control" type="ING.INGRESO_DET" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.MARCA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MARCA_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MARCA_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ASOC_MARCA".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.DET_SOLICITUD_PRODUCTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_TIPO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_BODEGA_ORIGEN".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_PRODUCTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_CANT_SOL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_CANT_ENTR".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_ESTADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DSOLP_UNIDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.CATEGORIA_PRODUCTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CAT_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CAT_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SUB_CAT".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.CATEGORIA_PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CLASIFICACION".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROD.COMPUESTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COMP_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COMP_CANTIDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COMP_UNIDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.MOVIMIENTO_KARDEX">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_TIPO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_CANTIDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_SALDO_ANT".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_COSTO_ING".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_PMP".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_TIPO_DOCUMENTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_CODIGO_DOCUMENTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RMOV_PROVEEDOR".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "REGISTRA".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.MAESTRO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.SOLICITUD_PRODUCTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SPROD_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SPROD_FECHA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SPROD_ESTADO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SPROD_USUARIO_INICIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "SPROD_USUARIO_DESTINO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CONTABILIZA_PROD".$value;?>" title=""  placeholder=".." class="form-control" type="EMP.CENTRO_COSTO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "LISTA_PRODUCTOS".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.DET_SOLICITUD_PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROC.UMEDIDA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "UMED_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "UMED_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "UMED_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "UMED_SIGLA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "MIDE".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF.PAIS">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PAIS_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PAIS_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROCEDENCIA".$value;?>" title=""  placeholder=".." class="form-control" type="ING.PROVEEDOR" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.PROVEEDOR">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_RUT".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_RUTDIG".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_CIUDAD".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_MAIL".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_DIRECCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_FONO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_CONTACTO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_SERVICIO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_CONDICION_PAGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_RANKING".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_GIRO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROV_LOG".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING_PROVEEDOR".$value;?>" title=""  placeholder=".." class="form-control" type="ING.INGRESO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_28".$value;?>" title=""  placeholder=".." class="form-control" type="ING.NOTA_CREDITO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.PRODUCTO_PROVEEDOR".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DOCUMENTOS">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DOC_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DOC_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DOC_TIPO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:short"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DOC_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_14".$value;?>" title=""  placeholder=".." class="form-control" type="MOVIMIENTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TELAS.COLORES">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COLOR_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COLOR_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COLOR_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COLOR_HTML".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TELAS.TELA_PROM">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TPROM_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TPROM_UMPESO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TPROM_UMLONG".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TPROM_PESO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TPROM_LONG".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TPROM_OBSERVACION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "PROM_MEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="PROC.PRODUCTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TELAS.TEXTURA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TEXTURA_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "TEXTURA_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "EMP.DEPARTAMENTO">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DPTO_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DPTO_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "GESTIONA_RECURSO".$value;?>" title=""  placeholder=".." class="form-control" type="EMP.CENTRO_COSTO" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF_ADUANAS">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ADU_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ADU_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF_AVANZADAS_ADUANERAS">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "AVAN_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "AVAN_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "AVAN_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "AVAN_CODIGOADUANA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF_CODIGOS_ARANCELARIOS">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ARAN_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ARAN_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ARAN_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ARAN_UMEDIDA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF_CONDICIONES_DE_VENTA">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CVEN_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CVEN_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "CVEN_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ZF_DESTINOS">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DES_CODIGO".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DES_NOMBRE".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "DES_DESCRIPCION".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:string"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.OC">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "OC_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_16".$value;?>" title=""  placeholder=".." class="form-control" type="ING.OC_DET" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_18".$value;?>" title=""  placeholder=".." class="form-control" type="ING.INGRESO" minOccurs="0" maxOccurs="unbounded"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "RELATIONSHIP_23".$value;?>" title=""  placeholder=".." class="form-control" type="ING.SOLICITUD_COMPRA" minOccurs="0" maxOccurs="unbounded"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.OC_DET">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "OC_DET_ID".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:long"  ></div>
  </xsd:element>
  
  <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "ING.PRODUCTO_PROVEEDOR">
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COMPRA_VALOR".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:double"  ></div>
   <div class="col-1 col-sm-4 col-md-2 col-lg-2"><label style="font-size: x-small;">CAMPO</label> </div><div class="col-6 col-sm-4 col-md-4  col-lg-4"><input type="text" id="<? echo  "COMPRA_FECHA".$value;?>" title=""  placeholder=".." class="form-control" type="xsd:date"  ></div>
  </xsd:element>

</xsd:schema>