
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cls_ing_compras
 * GENERATION DATE:  22.05.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_ing_compras.php
 * FOR MYSQL TABLE:  ing_compras
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_ing_compras { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $PROV_ID;   // (normal Attribute)
    var $ING_NUMERODOC2;   // (normal Attribute)
    var $ING_TIPODOC2;   // (normal Attribute)
    var $BOD_CODIGO;   // (normal Attribute)
    var $ING_FECHADOC;   // (normal Attribute)
    var $ing_fechadoc_fin;
    var $ING_MONEDA;   // (normal Attribute)
    var $ING_TIPODECAMBIO;   // (normal Attribute)
    var $ING_IVA;   // (normal Attribute)
    var $ING_TIPOPAGO;   // (normal Attribute)
    var $ING_ESTADO_PAGO;   // (normal Attribute)
    var $ING_ESTADO_DOC;   // (normal Attribute)
    var $ING_NETO;   // (normal Attribute)
    var $ING_TOTAL;   // (normal Attribute)
    var $ING_BODEGA_REC;   // (normal Attribute)
    var $ING_GENINGRESO;   // (normal Attribute)
    var $database; // Instance of class database
    var $arrcomp;

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cls_ing_compras() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getPROV_ID() {
        return $this->PROV_ID;
    }

    function getING_NUMERODOC2() {
        return $this->ING_NUMERODOC2;
    }

    function getING_TIPODOC2() {
        return $this->ING_TIPODOC2;
    }

    function getBOD_CODIGO() {
        return $this->BOD_CODIGO;
    }

    function getING_FECHADOC() {
        return $this->ING_FECHADOC;
    }

    function getING_MONEDA() {
        return $this->ING_MONEDA;
    }

    function getING_TIPODECAMBIO() {
        return $this->ING_TIPODECAMBIO;
    }

    function getING_IVA() {
        return $this->ING_IVA;
    }

    function getING_TIPOPAGO() {
        return $this->ING_TIPOPAGO;
    }

    function getING_ESTADO_PAGO() {
        return $this->ING_ESTADO_PAGO;
    }

    function getING_ESTADO_DOC() {
        return $this->ING_ESTADO_DOC;
    }

    function getING_NETO() {
        return $this->ING_NETO;
    }

    function getING_TOTAL() {
        return $this->ING_TOTAL;
    }

    function getING_BODEGA_REC() {
        return $this->ING_BODEGA_REC;
    }

    function getING_GENINGRESO() {
        return $this->ING_GENINGRESO;
    }

// **********************
// SETTER METHODS
// **********************


    function setPROV_ID($val) {
        $this->PROV_ID = $val;
    }

    function setING_NUMERODOC2($val) {
        $this->ING_NUMERODOC2 = $val;
    }

    function setING_TIPODOC2($val) {
        $this->ING_TIPODOC2 = $val;
    }

    function setBOD_CODIGO($val) {
        $this->BOD_CODIGO = $val;
    }

    function setING_FECHADOC($val) {
        $this->ING_FECHADOC = $val;
    }

    function setING_FECHADOC_FIN($val) {
        $this->ing_fechadoc_fin = $val;
    }

    function setING_MONEDA($val) {
        $this->ING_MONEDA = $val;
    }

    function setING_TIPODECAMBIO($val) {
        $this->ING_TIPODECAMBIO = $val;
    }

    function setING_IVA($val) {
        $this->ING_IVA = $val;
    }

    function setING_TIPOPAGO($val) {
        $this->ING_TIPOPAGO = $val;
    }

    function setING_ESTADO_PAGO($val) {
        $this->ING_ESTADO_PAGO = $val;
    }

    function setING_ESTADO_DOC($val) {
        $this->ING_ESTADO_DOC = $val;
    }

    function setING_NETO($val) {
        $this->ING_NETO = $val;
    }

    function setING_TOTAL($val) {
        $this->ING_TOTAL = $val;
    }

    function setING_BODEGA_REC($val) {
        $this->ING_BODEGA_REC = $val;
    }

    function setING_GENINGRESO($val) {
        $this->ING_GENINGRESO = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {

        $ing_numerodoc = $this->ING_NUMERODOC2;
        $ing_estado_doc = $this->ING_ESTADO_DOC;
        $ing_estado_pago = $this->ING_ESTADO_PAGO;
        $ing_tipodoc = $this->ING_TIPODOC2;
        $ing_fechadoc = $this->ING_FECHADOC;
        $ing_fechadoc_fin = $this->ing_fechadoc_fin;

        $sql = "SELECT * FROM ing_compras WHERE ";

        if ($ing_estado_doc != null) {
            $sql = $sql . "ING_ESTADO_DOC = '" . $ing_estado_doc . "' ";
        } else {
            $sql = $sql . "ING_ESTADO_DOC > '0' ";
        }
        if ($ing_estado_pago != null) {
            $sql = $sql . "ING_ESTADO_PAGO = '" . $ing_estado_pago . "' ";
        }
        if ($ing_numerodoc != null) {
            $sql = $sql . "ING_NUMERODOC2 = '" . $ing_numerodoc . "' ";
        }
        if ($ing_tipodoc != null) {
            $sql = $sql . "ING_TIPODOC2 = '" . $ing_tipodoc . "' ";
        }
        if ($solc_fecha != null) {
            if ($solc_fecha_fin != null) {
                $sql = $sql . "AND ING_FECHADOC BETWEEN '" . $ing_fechadoc . "' AND '" . $ing_fechadoc_fin . "' ";
            }
            $sql = $sql . "AND ING_FECHADOC = '" . $ing_fechadoc . "' ";
        }
        $result = $this->database->query($sql);
        $i = 0;
        while ($datos = $this->database->fetch_array($result)) {
            $this->arrcomp[$i]['PROV_ID'] = $datos['PROV_ID'];
            $this->arrcomp[$i]['ING_NUMERODOC2'] = $datos['ING_NUMERODOC2'];
            $this->arrcomp[$i]['ING_TIPODOC2'] = $datos['ING_TIPODOC2'];
            $this->arrcomp[$i]['BOD_CODIGO'] = $datos['BOD_CODIGO'];
            $this->arrcomp[$i]['ING_FECHADOC'] = $datos['ING_FECHADOC'];
            $this->arrcomp[$i]['ING_MONEDA'] = $datos['ING_MONEDA'];
            $this->arrcomp[$i]['ING_TIPODECAMBIO'] = $datos['ING_TIPODECAMBIO'];
            $this->arrcomp[$i]['ING_TIPOPAGO'] = $datos['ING_TIPOPAGO'];
            $this->arrcomp[$i]['ING_ESTADO_PAGO'] = $datos['ING_ESTADO_PAGO'];
            $this->arrcomp[$i]['ING_ESTADO_DOC'] = $datos['ING_ESTADO_DOC'];
            $this->arrcomp[$i]['ING_NETO'] = $datos['ING_NETO'];
            $this->arrcomp[$i]['ING_TOTAL'] = $datos['ING_TOTAL'];
            $this->arrcomp[$i]['ING_BODEGA_REC'] = $datos['ING_BODEGA_REC'];
            $this->arrcomp[$i]['ING_GENINGRESO'] = $datos['ING_GENINGRESO'];
            $i++;
        }
    }

// **********************
// DELETE
// **********************

    function delete() {
        $ing_numerodoc = $this->ING_NUMERODOC2;
        $sql = "DELETE FROM ing_compras WHERE  ING_NUMERODOC2 = '$ing_numerodoc' ;";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {


        $sql = "INSERT INTO ing_compras ( PROV_ID,ING_TIPODOC2,BOD_CODIGO,ING_FECHADOC,ING_MONEDA,ING_TIPODECAMBIO,ING_IVA,ING_TIPOPAGO,ING_ESTADO_PAGO,ING_ESTADO_DOC,ING_NETO,ING_TOTAL,ING_BODEGA_REC,ING_GENINGRESO ) VALUES ( '$this->PROV_ID','$this->ING_TIPODOC2','$this->BOD_CODIGO','$this->ING_FECHADOC','$this->ING_MONEDA','$this->ING_TIPODECAMBIO','$this->ING_IVA','$this->ING_TIPOPAGO','$this->ING_ESTADO_PAGO','$this->ING_ESTADO_DOC','$this->ING_NETO','$this->ING_TOTAL','$this->ING_BODEGA_REC','$this->ING_GENINGRESO' )";
        $result = $this->database->query($sql);
    }

// **********************
// UPDATE
// **********************

    function update($op) {

        $ing_numerodoc = $this->ING_ESTADO_DOC;

        switch ($op) {
            case 0:
                $sql = " UPDATE ing_compras SET  PROV_ID = '$this->PROV_ID', ING_TIPODOC2 = '$this->ING_TIPODOC2',BOD_CODIGO = '$this->BOD_CODIGO',"
                        . "ING_FECHADOC = '$this->ING_FECHADOC',ING_MONEDA = '$this->ING_MONEDA',ING_TIPODECAMBIO = '$this->ING_TIPODECAMBIO',ING_IVA = '$this->ING_IVA',"
                        . "ING_TIPOPAGO = '$this->ING_TIPOPAGO',ING_ESTADO_PAGO = '$this->ING_ESTADO_PAGO',ING_ESTADO_DOC = '$this->ING_ESTADO_DOC',"
                        . "ING_NETO = '$this->ING_NETO',ING_TOTAL = '$this->ING_TOTAL',ING_BODEGA_REC = '$this->ING_BODEGA_REC',ING_GENINGRESO = '$this->ING_GENINGRESO' "
                        . "WHERE  ING_NUMERODOC2 = '$ing_numerodoc' ";
                break;
            case 1:
                $sql = " UPDATE ing_compras SET ING_ESTADO_PAGO = '$this->ING_ESTADO_PAGO' WHERE  ING_NUMERODOC2 = '$ing_numerodoc' ";
                break;
            case 2:
                $sql = " UPDATE ing_compras SET ING_ESTADO_DOC = '$this->ING_ESTADO_DOC' WHERE  ING_NUMERODOC2 = '$ing_numerodoc' ";
                break;
        }
        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
