
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cl_proc_umedida
 * GENERATION DATE:  02.05.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cl_proc_umedida.php
 * FOR MYSQL TABLE:  proc_umedida
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

include_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cl_proc_umedida { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $umed_codigo;   // KEY ATTR. WITH AUTOINCREMENT
    var $umed_nombre;   // (normal Attribute)
    var $umed_descripcion;   // (normal Attribute)
    var $umed_sigla;   // (normal Attribute)
    var $database; // Instance of class database
    var $arrprocume;

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cl_proc_umedida() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getumed_codigo() {
        return $this->umed_codigo;
    }

    function getumed_nombre() {
        return $this->umed_nombre;
    }

    function getumed_descripcion() {
        return $this->umed_descripcion;
    }

    function getumed_sigla() {
        return $this->umed_sigla;
    }

// **********************
// SETTER METHODS
// **********************


    function setumed_codigo($val) {
        $this->umed_codigo = $val;
    }

    function setumed_nombre($val) {
        $this->umed_nombre = $val;
    }

    function setumed_descripcion($val) {
        $this->umed_descripcion = $val;
    }

    function setumed_sigla($val) {
        $this->umed_sigla = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {
        $umed_codigo = $this->umed_codigo;
        $sql = "SELECT * FROM proc_umedida WHERE umed_codigo = $umed_codigo;";
        $result = $this->database->query($sql);
//        $result = $this->database->result;
//        $row = mysql_fetch_object($result);


//        $this->umed_codigo = $row->umed_codigo;
//
//        $this->umed_nombre = $row->umed_nombre;
//
//        $this->umed_descripcion = $row->umed_descripcion;
//
//        $this->umed_sigla = $row->umed_sigla;
        $i=0;
        
        while ($datos = $this->database->fetch_array($result)) {
            $this->arrprocume[$i]['umed_codigo'] = $datos['umed_codigo'];
            $this->arrprocume[$i]['umed_nombre'] = $datos['umed_nombre'];
            $this->arrprocume[$i]['umed_descripcion'] = $datos['umed_descripcion'];
            $this->arrprocume[$i]['umed_sigla'] = $datos['umed_sigla'];
        }
    }

// **********************
// DELETE
// **********************

    function delete() {
        $umed_codigo = $this->umed_codigo;

        $sql = "DELETE FROM proc_umedida WHERE umed_codigo = $umed_codigo;";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {

        $sql = "INSERT INTO proc_umedida ( umed_nombre,umed_descripcion,umed_sigla ) VALUES ( '$this->umed_nombre','$this->umed_descripcion','$this->umed_sigla' )";
        $result = $this->database->query($sql);
        $this->umed_codigo = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update() {
        $umed_codigo = $this->umed_codigo;

        $sql = " UPDATE proc_umedida SET  umed_nombre = '$this->umed_nombre',umed_descripcion = '$this->umed_descripcion',umed_sigla = '$this->umed_sigla' WHERE umed_codigo = $umed_codigo ";

        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
