
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cl_proc_producto
 * GENERATION DATE:  02.05.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cl_proc_producto.php
 * FOR MYSQL TABLE:  proc_producto
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cl_proc_producto { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $prod_codigo;   // KEY ATTR. WITH AUTOINCREMENT
    var $marca_id;   // (normal Attribute)
    var $umed_codigo;   // (normal Attribute)
    var $pro_prod_codigo;   // (normal Attribute)
    var $cat_id;   // (normal Attribute)
    var $tprom_id;   // (normal Attribute)
    var $prod_codigobarra;   // (normal Attribute)
    var $prod_nombre;   // (normal Attribute)
    var $prod_tipo;   // (normal Attribute)
    var $prod_informacionadic;   // (normal Attribute)
    var $prod_codigoarancelario;   // (normal Attribute)
    var $prod_precio1;   // (normal Attribute)
    var $prod_precio2;   // (normal Attribute)
    var $prod_ley18211;   // (normal Attribute)
    var $prod_fabricadozf;   // (normal Attribute)
    var $prod_descripcion;   // (normal Attribute)
    var $prod_modelo;   // (normal Attribute)
    var $prod_umedida_cant;   // (normal Attribute)
    var $prod_sist_medida;   // (normal Attribute)
    var $prod_color;   // (normal Attribute)
    var $prod_peso_ctrol;   // (normal Attribute)
    var $prod_largo;   // (normal Attribute)
    var $prod_ancho;   // (normal Attribute)
    var $prod_alto;   // (normal Attribute)
    var $prod_estado;   // (normal Attribute)
    var $prod_servicio;   // (normal Attribute)
    var $prod_imagen;   // (normal Attribute)
    var $prod_imagen2;   // (normal Attribute)
    var $prod_oferta;   // (normal Attribute)
    var $prod_precio_oferta;   // (normal Attribute)
    var $prod_precio_pieza;   // (normal Attribute)
    var $prod_sist_medida2;   // (normal Attribute)
    var $database; // Instance of class database
    var $arrprod;

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cl_proc_producto() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getprod_codigo() {
        return $this->prod_codigo;
    }

    function getmarca_id() {
        return $this->marca_id;
    }

    function getumed_codigo() {
        return $this->umed_codigo;
    }

    function getpro_prod_codigo() {
        return $this->pro_prod_codigo;
    }

    function getcat_id() {
        return $this->cat_id;
    }

    function gettprom_id() {
        return $this->tprom_id;
    }

    function getprod_codigobarra() {
        return $this->prod_codigobarra;
    }

    function getprod_nombre() {
        return $this->prod_nombre;
    }

    function getprod_tipo() {
        return $this->prod_tipo;
    }

    function getprod_informacionadic() {
        return $this->prod_informacionadic;
    }

    function getprod_codigoarancelario() {
        return $this->prod_codigoarancelario;
    }

    function getprod_precio1() {
        return $this->prod_precio1;
    }

    function getprod_precio2() {
        return $this->prod_precio2;
    }

    function getprod_ley18211() {
        return $this->prod_ley18211;
    }

    function getprod_fabricadozf() {
        return $this->prod_fabricadozf;
    }

    function getprod_descripcion() {
        return $this->prod_descripcion;
    }

    function getprod_modelo() {
        return $this->prod_modelo;
    }

    function getprod_umedida_cant() {
        return $this->prod_umedida_cant;
    }

    function getprod_sist_medida() {
        return $this->prod_sist_medida;
    }

    function getprod_color() {
        return $this->prod_color;
    }

    function getprod_peso_ctrol() {
        return $this->prod_peso_ctrol;
    }

    function getprod_largo() {
        return $this->prod_largo;
    }

    function getprod_ancho() {
        return $this->prod_ancho;
    }

    function getprod_alto() {
        return $this->prod_alto;
    }

    function getprod_estado() {
        return $this->prod_estado;
    }

    function getprod_servicio() {
        return $this->prod_servicio;
    }

    function getprod_imagen() {
        return $this->prod_imagen;
    }

    function getprod_imagen2() {
        return $this->prod_imagen2;
    }

    function getprod_oferta() {
        return $this->prod_oferta;
    }

    function getprod_precio_oferta() {
        return $this->prod_precio_oferta;
    }

    function getprod_precio_pieza() {
        return $this->prod_precio_pieza;
    }

    function getprod_sist_medida2() {
        return $this->prod_sist_medida2;
    }

// **********************
// SETTER METHODS
// **********************


    function setprod_codigo($val) {
        $this->prod_codigo = $val;
    }

    function setmarca_id($val) {
        $this->marca_id = $val;
    }

    function setumed_codigo($val) {
        $this->umed_codigo = $val;
    }

    function setpro_prod_codigo($val) {
        $this->pro_prod_codigo = $val;
    }

    function setcat_id($val) {
        $this->cat_id = $val;
    }

    function settprom_id($val) {
        $this->tprom_id = $val;
    }

    function setprod_codigobarra($val) {
        $this->prod_codigobarra = $val;
    }

    function setprod_nombre($val) {
        $this->prod_nombre = $val;
    }

    function setprod_tipo($val) {
        $this->prod_tipo = $val;
    }

    function setprod_informacionadic($val) {
        $this->prod_informacionadic = $val;
    }

    function setprod_codigoarancelario($val) {
        $this->prod_codigoarancelario = $val;
    }

    function setprod_precio1($val) {
        $this->prod_precio1 = $val;
    }

    function setprod_precio2($val) {
        $this->prod_precio2 = $val;
    }

    function setprod_ley18211($val) {
        $this->prod_ley18211 = $val;
    }

    function setprod_fabricadozf($val) {
        $this->prod_fabricadozf = $val;
    }

    function setprod_descripcion($val) {
        $this->prod_descripcion = $val;
    }

    function setprod_modelo($val) {
        $this->prod_modelo = $val;
    }

    function setprod_umedida_cant($val) {
        $this->prod_umedida_cant = $val;
    }

    function setprod_sist_medida($val) {
        $this->prod_sist_medida = $val;
    }

    function setprod_color($val) {
        $this->prod_color = $val;
    }

    function setprod_peso_ctrol($val) {
        $this->prod_peso_ctrol = $val;
    }

    function setprod_largo($val) {
        $this->prod_largo = $val;
    }

    function setprod_ancho($val) {
        $this->prod_ancho = $val;
    }

    function setprod_alto($val) {
        $this->prod_alto = $val;
    }

    function setprod_estado($val) {
        $this->prod_estado = $val;
    }

    function setprod_servicio($val) {
        $this->prod_servicio = $val;
    }

    function setprod_imagen($val) {
        $this->prod_imagen = $val;
    }

    function setprod_imagen2($val) {
        $this->prod_imagen2 = $val;
    }

    function setprod_oferta($val) {
        $this->prod_oferta = $val;
    }

    function setprod_precio_oferta($val) {
        $this->prod_precio_oferta = $val;
    }

    function setprod_precio_pieza($val) {
        $this->prod_precio_pieza = $val;
    }

    function setprod_sist_medida2($val) {
        $this->prod_sist_medida2 = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {
        $prod_codigo = $this->pro_prod_codigo;
        $prod_estado = $this->prod_estado;

        $sql = "SELECT * FROM proc_producto WHERE ";
        if ($prod_estado != null) {
            $sql = $sql . "AND prod_estado = '" . $prod_estado . "' ";
        } else {
            $sql = $sql . "AND prod_estado > '0' ";
        }
        if ($cat_id != null) {
            $sql = $sql . "AND cat_id = '" . $cat_id . "' ";
        }
        if ($prod_tipo != null) {
            $sql = $sql . "AND prod_tipo = '" . $prod_tipo . "' ";
        }
        if ($prod_servicio != null) {
            $sql = $sql . "AND prod_servicio = '" . $prod_servicio . "' ";
        }
        $result = $this->database->query($sql);

        $i = 0;
        while ($datos = $this->database->fetch_array($result)) {
            $this->arrprod[$i]['prod_codigo'] = $datos['prod_codigo'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['umed_codigo'] = $datos['umed_codigo'];
            $this->arrprod[$i]['pro_prod_codigo'] = $datos['pro_prod_codigo'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
            $this->arrprod[$i]['marca_id'] = $datos['marca_id'];
        }
    }

// **********************
// DELETE
// **********************

    function delete() {
        $prod_codigo = $this->pro_prod_codigo;
        $sql = "DELETE FROM proc_producto WHERE prod_codigo = $prod_codigo;";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {

        $sql = "INSERT INTO proc_producto ( marca_id,umed_codigo,pro_prod_codigo,cat_id,tprom_id,prod_codigobarra,prod_nombre,prod_tipo,prod_informacionadic,prod_codigoarancelario,prod_precio1,prod_precio2,prod_ley18211,prod_fabricadozf,prod_descripcion,prod_modelo,prod_umedida_cant,prod_sist_medida,prod_color,prod_peso_ctrol,prod_largo,prod_ancho,prod_alto,prod_estado,prod_servicio,prod_imagen,prod_imagen2,prod_oferta,prod_precio_oferta,prod_precio_pieza,prod_sist_medida2 ) VALUES ( '$this->marca_id','$this->umed_codigo','$this->pro_prod_codigo','$this->cat_id','$this->tprom_id','$this->prod_codigobarra','$this->prod_nombre','$this->prod_tipo','$this->prod_informacionadic','$this->prod_codigoarancelario','$this->prod_precio1','$this->prod_precio2','$this->prod_ley18211','$this->prod_fabricadozf','$this->prod_descripcion','$this->prod_modelo','$this->prod_umedida_cant','$this->prod_sist_medida','$this->prod_color','$this->prod_peso_ctrol','$this->prod_largo','$this->prod_ancho','$this->prod_alto','$this->prod_estado','$this->prod_servicio','$this->prod_imagen','$this->prod_imagen2','$this->prod_oferta','$this->prod_precio_oferta','$this->prod_precio_pieza','$this->prod_sist_medida2' )";
        $result = $this->database->query($sql);
        $this->prod_codigo = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update() {
        $prod_codigo = $this->pro_prod_codigo;


        $sql = " UPDATE proc_producto SET  marca_id = '$this->marca_id',umed_codigo = '$this->umed_codigo',pro_prod_codigo = '$this->pro_prod_codigo',cat_id = '$this->cat_id',tprom_id = '$this->tprom_id',prod_codigobarra = '$this->prod_codigobarra',prod_nombre = '$this->prod_nombre',prod_tipo = '$this->prod_tipo',prod_informacionadic = '$this->prod_informacionadic',prod_codigoarancelario = '$this->prod_codigoarancelario',prod_precio1 = '$this->prod_precio1',prod_precio2 = '$this->prod_precio2',prod_ley18211 = '$this->prod_ley18211',prod_fabricadozf = '$this->prod_fabricadozf',prod_descripcion = '$this->prod_descripcion',prod_modelo = '$this->prod_modelo',prod_umedida_cant = '$this->prod_umedida_cant',prod_sist_medida = '$this->prod_sist_medida',prod_color = '$this->prod_color',prod_peso_ctrol = '$this->prod_peso_ctrol',prod_largo = '$this->prod_largo',prod_ancho = '$this->prod_ancho',prod_alto = '$this->prod_alto',prod_estado = '$this->prod_estado',prod_servicio = '$this->prod_servicio',prod_imagen = '$this->prod_imagen',prod_imagen2 = '$this->prod_imagen2',prod_oferta = '$this->prod_oferta',prod_precio_oferta = '$this->prod_precio_oferta',prod_precio_pieza = '$this->prod_precio_pieza',prod_sist_medida2 = '$this->prod_sist_medida2' WHERE prod_codigo = $prod_codigo ";

        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
