
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cls_ing_oc
 * GENERATION DATE:  13.04.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_ing_oc.php
 * FOR MYSQL TABLE:  ing_oc
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_ing_oc { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $oc_id;   // KEY ATTR. WITH AUTOINCREMENT
    var $prov_id;   // (normal Attribute)
    var $oc_codigo;   // (normal Attribute)
    var $oc_tipo;   // (normal Attribute)
    var $oc_empresa;   // (normal Attribute)
    var $oc_log;   // (normal Attribute)
    var $oc_estado;   // (normal Attribute)
    var $oc_fecha_entrega;   // (normal Attribute)
    var $oc_fecha_entrega_fin;
    var $oc_solicitante;   // (normal Attribute)
    var $oc_observacion;   // (normal Attribute)
    var $oc_neto;   // (normal Attribute)
    var $oc_iva;   // (normal Attribute)
    var $oc_total;   // (normal Attribute)
    var $oc_forma_pago;   // (normal Attribute)
    var $oc_condiciones;   // (normal Attribute)
    var $oc_rut_emision;   // (normal Attribute)
    var $oc_rut_aprobacion;   // (normal Attribute)
    var $oc_cheque_adjunto;   // (normal Attribute)
    var $oc_descuento;   // (normal Attribute)
    var $oc_tipo_descuento;   // (normal Attribute)
    var $oc_impuesto;   // (normal Attribute)
    var $oc_gasto_envio;   // (normal Attribute)
    var $oc_estado_pago;   // (normal Attribute)
    var $database; // Instance of class database
    var $arringoc;

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cls_ing_oc() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getprov_id() {
        return $this->prov_id;
    }

    function getoc_id() {
        return $this->oc_id;
    }

    function getoc_codigo() {
        return $this->oc_codigo;
    }

    function getoc_tipo() {
        return $this->oc_tipo;
    }

    function getoc_empresa() {
        return $this->oc_empresa;
    }

    function getoc_log() {
        return $this->oc_log;
    }

    function getoc_estado() {
        return $this->oc_estado;
    }

    function getoc_fecha_entrega() {
        return $this->oc_fecha_entrega;
    }

    function getoc_solicitante() {
        return $this->oc_solicitante;
    }

    function getoc_observacion() {
        return $this->oc_observacion;
    }

    function getoc_neto() {
        return $this->oc_neto;
    }

    function getoc_iva() {
        return $this->oc_iva;
    }

    function getoc_total() {
        return $this->oc_total;
    }

    function getoc_forma_pago() {
        return $this->oc_forma_pago;
    }

    function getoc_condiciones() {
        return $this->oc_condiciones;
    }

    function getoc_rut_emision() {
        return $this->oc_rut_emision;
    }

    function getoc_rut_aprobacion() {
        return $this->oc_rut_aprobacion;
    }

    function getoc_cheque_adjunto() {
        return $this->oc_cheque_adjunto;
    }

    function getoc_descuento() {
        return $this->oc_descuento;
    }

    function getoc_tipo_descuento() {
        return $this->oc_tipo_descuento;
    }

    function getoc_impuesto() {
        return $this->oc_impuesto;
    }

    function getoc_gasto_envio() {
        return $this->oc_gasto_envio;
    }

    function getoc_estado_pago() {
        return $this->oc_estado_pago;
    }

// **********************
// SETTER METHODS
// **********************


    function setprov_id($val) {
        $this->prov_id = $val;
    }

    function setoc_id($val) {
        $this->oc_id = $val;
    }

    function setoc_codigo($val) {
        $this->oc_codigo = $val;
    }

    function setoc_tipo($val) {
        $this->oc_tipo = $val;
    }

    function setoc_empresa($val) {
        $this->oc_empresa = $val;
    }

    function setoc_log($val) {
        $this->oc_log = $val;
    }

    function setoc_estado($val) {
        $this->oc_estado = $val;
    }

    function setoc_fecha_entrega($val) {
        $this->oc_fecha_entrega = $val;
    }

    function setoc_fecha_entrega_fin($val) {
        $this->oc_fecha_entrega_fin = $val;
    }

    function setoc_solicitante($val) {
        $this->oc_solicitante = $val;
    }

    function setoc_observacion($val) {
        $this->oc_observacion = $val;
    }

    function setoc_neto($val) {
        $this->oc_neto = $val;
    }

    function setoc_iva($val) {
        $this->oc_iva = $val;
    }

    function setoc_total($val) {
        $this->oc_total = $val;
    }

    function setoc_forma_pago($val) {
        $this->oc_forma_pago = $val;
    }

    function setoc_condiciones($val) {
        $this->oc_condiciones = $val;
    }

    function setoc_rut_emision($val) {
        $this->oc_rut_emision = $val;
    }

    function setoc_rut_aprobacion($val) {
        $this->oc_rut_aprobacion = $val;
    }

    function setoc_cheque_adjunto($val) {
        $this->oc_cheque_adjunto = $val;
    }

    function setoc_descuento($val) {
        $this->oc_descuento = $val;
    }

    function setoc_tipo_descuento($val) {
        $this->oc_tipo_descuento = $val;
    }

    function setoc_impuesto($val) {
        $this->oc_impuesto = $val;
    }

    function setoc_gasto_envio($val) {
        $this->oc_gasto_envio = $val;
    }

    function setoc_estado_pago($val) {
        $this->oc_estado_pago = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {

        $oc_id = $this->oc_id;
        $prov_id = $this->prov_id;
        $oc_tipo = $this->oc_tipo;
        $oc_estado = $this->oc_estado;
        $oc_fecha_entrega = $this->oc_fecha_entrega;
        $oc_fecha_entrega_fin = $this->oc_fecha_entrega_fin;

        $sql = "SELECT * FROM ing_oc p LEFT JOIN efectua_compra h ON p.oc_id=h.oc_id WHERE ";

        if ($oc_estado != null) {
            $sql = $sql . "p.oc_estado = '" . $oc_estado . "' ";
        } else {
            $sql = $sql . "p.oc_estado > '0' ";
        }
        if ($oc_id != null) {
            $sql = $sql . "AND p.oc_id = '" . $oc_id . "' ";
        }
        if ($prov_id != null) {
            $sql = $sql . "AND p.prov_id = '" . $prov_id . "' ";
        }
        if ($oc_tipo != null) {
            $sql = $sql . "AND p.oc_tipo = '" . $oc_tipo . "' ";
        }
        if ($oc_fecha_entrega != null) {
            if ($oc_fecha_entrega_fin != null) {
                $sql = $sql . "AND P.oc_fecha_entrega BETWEEN '" . $oc_fecha_entrega . "' AND '" . $oc_fecha_entrega_fin . "' ";
            }
            $sql = $sql . "AND P.oc_fecha_entrega = '" . $oc_fecha_entrega . "' ";
        }

        $result = $this->database->query($sql);
//        $result = $this->database->result;
//        $row = mysql_fetch_object($result);

        $i = 0;
        while ($datos = $this->database->fetch_array($result)) {
            $this->arringoc[$i]['prov_id'] = $datos['prov_id'];
            $this->arringoc[$i]['oc_id'] = $datos['oc_id'];
            $this->arringoc[$i]['oc_codigo'] = $datos['oc_codigo'];
            $this->arringoc[$i]['oc_tipo'] = $datos['oc_tipo'];
            $this->arringoc[$i]['oc_empresa'] = $datos['oc_empresa'];
            $this->arringoc[$i]['oc_log'] = $datos['oc_log'];
            $this->arringoc[$i]['oc_estado'] = $datos['oc_estado'];
            $this->arringoc[$i]['oc_fecha_entrega'] = $datos['oc_fecha_entrega'];
            $this->arringoc[$i]['oc_solicitante'] = $datos['oc_solicitante'];
            $this->arringoc[$i]['oc_observacion'] = $datos['oc_observacion'];
            $this->arringoc[$i]['oc_neto'] = $datos['oc_neto'];
            $this->arringoc[$i]['oc_iva'] = $datos['oc_iva'];
            $this->arringoc[$i]['oc_total'] = $datos['oc_total'];
            $this->arringoc[$i]['oc_forma_pago'] = $datos['oc_forma_pago'];
            $this->arringoc[$i]['oc_condiciones'] = $datos['oc_condiciones'];
            $this->arringoc[$i]['oc_tipo_descuento'] = $datos['oc_tipo_descuento'];
            $this->arringoc[$i]['oc_impuesto'] = $datos['oc_impuesto'];
            $this->arringoc[$i]['oc_gasto_envio'] = $datos['oc_gasto_envio'];
            $this->arringoc[$i]['solc_id'] = $datos['solc_id'];
            $i++;
        }

//        $this->prov_id = $row->prov_id;
//
//        $this->oc_id = $row->oc_id;
//
//        $this->oc_codigo = $row->oc_codigo;
//
//        $this->oc_tipo = $row->oc_tipo;
//
//        $this->oc_empresa = $row->oc_empresa;
//
//        $this->oc_log = $row->oc_log;
//
//        $this->oc_estado = $row->oc_estado;
//
//        $this->oc_fecha_entrega = $row->oc_fecha_entrega;
//
//        $this->oc_solicitante = $row->oc_solicitante;
//
//        $this->oc_observacion = $row->oc_observacion;
//
//        $this->oc_neto = $row->oc_neto;
//
//        $this->oc_iva = $row->oc_iva;
//
//        $this->oc_total = $row->oc_total;
//
//        $this->oc_forma_pago = $row->oc_forma_pago;
//
//        $this->oc_condiciones = $row->oc_condiciones;
//
//        $this->oc_rut_emision = $row->oc_rut_emision;
//
//        $this->oc_rut_aprobacion = $row->oc_rut_aprobacion;
//
//        $this->oc_cheque_adjunto = $row->oc_cheque_adjunto;
//
//        $this->oc_descuento = $row->oc_descuento;
//
//        $this->oc_tipo_descuento = $row->oc_tipo_descuento;
//
//        $this->oc_impuesto = $row->oc_impuesto;
//
//        $this->oc_gasto_envio = $row->oc_gasto_envio;
//
//        $this->oc_estado_pago = $row->oc_estado_pago;
    }

// **********************
// DELETE
// **********************

    function delete() {

        $oc_id = $this->oc_id;

        $sql = "DELETE FROM ing_oc WHERE oc_id = '$oc_id';";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {

        $sql = "INSERT INTO ing_oc ( prov_id,oc_codigo,oc_tipo,oc_empresa,oc_log,oc_estado,oc_fecha_entrega,"
                . "oc_solicitante,oc_observacion,oc_neto,oc_iva,oc_total,oc_forma_pago,oc_condiciones,oc_rut_emision,"
                . "oc_rut_aprobacion,oc_cheque_adjunto,oc_descuento,oc_tipo_descuento,oc_impuesto,oc_gasto_envio,oc_estado_pago ) "
                . "VALUES ( '$this->prov_id','$this->oc_codigo','$this->oc_tipo','$this->oc_empresa','$this->oc_log','$this->oc_estado',"
                . "'$this->oc_fecha_entrega','$this->oc_solicitante','$this->oc_observacion','$this->oc_neto','$this->oc_iva','$this->oc_total',"
                . "'$this->oc_forma_pago','$this->oc_condiciones','$this->oc_rut_emision','$this->oc_rut_aprobacion','$this->oc_cheque_adjunto',"
                . "'$this->oc_descuento','$this->oc_tipo_descuento','$this->oc_impuesto','$this->oc_gasto_envio','$this->oc_estado_pago' )";
        $result = $this->database->query($sql);
        $this->oc_id = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update($opc) {

        $oc_id = $this->oc_id;

        switch ($opc) {
            case 0:
                $sql = " UPDATE ing_oc SET  oc_codigo = '$this->oc_codigo',oc_tipo = '$this->oc_tipo',oc_empresa = '$this->oc_empresa',"
                        . "oc_estado = '$this->oc_estado',oc_fecha_entrega = '$this->oc_fecha_entrega',oc_observacion = '$this->oc_observacion',"
                        . "oc_neto = '$this->oc_neto',oc_iva = '$this->oc_iva',oc_total = '$this->oc_total',oc_forma_pago = '$this->oc_forma_pago',"
                        . "oc_condiciones = '$this->oc_condiciones',oc_rut_emision = '$this->oc_rut_emision',oc_rut_aprobacion = '$this->oc_rut_aprobacion',"
                        . "oc_cheque_adjunto = '$this->oc_cheque_adjunto',oc_descuento = '$this->oc_descuento',oc_tipo_descuento = '$this->oc_tipo_descuento',"
                        . "oc_impuesto = '$this->oc_impuesto',oc_gasto_envio = '$this->oc_gasto_envio',oc_estado_pago = '$this->oc_estado_pago' "
                        . "WHERE oc_id = '$oc_id' ";
                break;
            case 1:
                $sql = " UPDATE ing_oc SET  oc_estado = '$this->oc_estado' WHERE oc_id = '$oc_id' ";
                break;
        }
        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
