
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cl_ing_ingreso
 * GENERATION DATE:  02.05.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cl_ing_ingreso.php
 * FOR MYSQL TABLE:  ing_ingreso
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

include_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cl_ing_ingreso { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $ing_correlativo;   // KEY ATTR. WITH AUTOINCREMENT
    var $prov_id;   // (normal Attribute)
    var $ing_numerodoc;   // (normal Attribute)
    var $ing_tipodoc;   // (normal Attribute)
    var $ing_fechadoc;   // (normal Attribute)
    var $ing_fechadoc_fin;
    var $ing_fechavisacion;   // (normal Attribute)
    var $ing_fechavisacion_fin;
    var $ing_numerovisacion;   // (normal Attribute)
    var $ing_moneda;   // (normal Attribute)
    var $ing_tipodecambio;   // (normal Attribute)
    var $ing_iva;   // (normal Attribute)
    var $ing_ciftotal;   // (normal Attribute)
    var $ing_costototal;   // (normal Attribute)
    var $ing_viutotal;   // (normal Attribute)
    var $ing_estado_pago;   // (normal Attribute)
    var $ing_estado_doc;   // (normal Attribute)
    var $ing_neto;   // (normal Attribute)
    var $ing_total;   // (normal Attribute)
    var $ing_tipodocsve;   // (normal Attribute)
    var $ing_bodega_rec;   // (normal Attribute)
    var $database; // Instance of class database
    var $arringreso;

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cl_ing_ingreso() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getprov_id() {
        return $this->prov_id;
    }

    function geting_numerodoc() {
        return $this->ing_numerodoc;
    }

    function geting_tipodoc() {
        return $this->ing_tipodoc;
    }

    function geting_correlativo() {
        return $this->ing_correlativo;
    }

    function geting_fechadoc() {
        return $this->ing_fechadoc;
    }

    function geting_fechavisacion() {
        return $this->ing_fechavisacion;
    }

    function geting_numerovisacion() {
        return $this->ing_numerovisacion;
    }

    function geting_moneda() {
        return $this->ing_moneda;
    }

    function geting_tipodecambio() {
        return $this->ing_tipodecambio;
    }

    function geting_iva() {
        return $this->ing_iva;
    }

    function geting_ciftotal() {
        return $this->ing_ciftotal;
    }

    function geting_costototal() {
        return $this->ing_costototal;
    }

    function geting_viutotal() {
        return $this->ing_viutotal;
    }

    function geting_estado_pago() {
        return $this->ing_estado_pago;
    }

    function geting_estado_doc() {
        return $this->ing_estado_doc;
    }

    function geting_neto() {
        return $this->ing_neto;
    }

    function geting_total() {
        return $this->ing_total;
    }

    function geting_tipodocsve() {
        return $this->ing_tipodocsve;
    }

    function geting_bodega_rec() {
        return $this->ing_bodega_rec;
    }

// **********************
// SETTER METHODS
// **********************


    function setprov_id($val) {
        $this->prov_id = $val;
    }

    function seting_numerodoc($val) {
        $this->ing_numerodoc = $val;
    }

    function seting_tipodoc($val) {
        $this->ing_tipodoc = $val;
    }

    function seting_correlativo($val) {
        $this->ing_correlativo = $val;
    }

    function seting_fechadoc($val) {
        $this->ing_fechadoc = $val;
    }

    function seting_fechavisacion($val) {
        $this->ing_fechavisacion = $val;
    }

    function seting_numerovisacion($val) {
        $this->ing_numerovisacion = $val;
    }

    function seting_moneda($val) {
        $this->ing_moneda = $val;
    }

    function seting_tipodecambio($val) {
        $this->ing_tipodecambio = $val;
    }

    function seting_iva($val) {
        $this->ing_iva = $val;
    }

    function seting_ciftotal($val) {
        $this->ing_ciftotal = $val;
    }

    function seting_costototal($val) {
        $this->ing_costototal = $val;
    }

    function seting_viutotal($val) {
        $this->ing_viutotal = $val;
    }

    function seting_estado_pago($val) {
        $this->ing_estado_pago = $val;
    }

    function seting_estado_doc($val) {
        $this->ing_estado_doc = $val;
    }

    function seting_neto($val) {
        $this->ing_neto = $val;
    }

    function seting_total($val) {
        $this->ing_total = $val;
    }

    function seting_tipodocsve($val) {
        $this->ing_tipodocsve = $val;
    }

    function seting_bodega_rec($val) {
        $this->ing_bodega_rec = $val;
    }

    function seting_fechadoc_fin($val) {
        $this->ing_fechadoc_fin = $val;
    }

    function seting_fechavisacion_fin($val) {
        $this->ing_fechavisacion_fin = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {
        $ing_numerodoc = $this->ing_numerodoc;
        $ing_estado_doc = $this->ing_estado_doc;
        $prov_id = $this->prov_id;
        $ing_tipodoc = $this->ing_tipodoc;
        $ing_correlativo = $this->ing_correlativo;
        $ing_fechadoc = $this->ing_fechadoc;
        $ing_fechadoc_fin = $this->ing_fechadoc_fin;
        $ing_fechavisacion = $this->ing_fechavisacion;
        $ing_fechavisacion_fin = $this->ing_fechavisacion_fin;


        $sql = "SELECT * FROM ing_ingreso p LEFT JOIN ingreso_compra h ON p.ing_numerodoc = h.ing_numerodoc WHERE ";
        $result = $this->database->query($sql);
//        $result = $this->database->result;
//        $row = mysql_fetch_object($result);
        if ($solc_estado != null) {
            $sql = $sql . "p.ing_estado_doc = '" . $ing_estado_doc . "' ";
        } else {
            $sql = $sql . "p.ing_estado_doc > '0' ";
        }
        if ($ing_numerodoc != null) {
            $sql = $sql . "AND p.ing_numerodoc = '" . $ing_numerodoc . "' ";
        }
        if ($prov_id != null) {
            $sql = $sql . "AND p.prov_id = '" . $prov_id . "' ";
        }
        if ($ing_numerodoc != null) {
            $sql = $sql . "AND p.ing_tipodoc = '" . $ing_tipodoc . "' ";
        }
        if ($ing_numerodoc != null) {
            $sql = $sql . "AND p.ing_correlativo = '" . $ing_correlativo . "' ";
        }
        if ($ing_fechadoc != null) {
            if ($ing_fechadoc_fin != null) {
                $sql = $sql . "AND P.ing_fechadoc BETWEEN '" . $ing_fechadoc . "' AND '" . $ing_fechadoc_fin . "' ";
            }
            $sql = $sql . "AND P.ing_fechadoc = '" . $solc_fecha . "' ";
        }
        if ($ing_fechavisacion != null) {
            if ($ing_fechavisacion_fin != null) {
                $sql = $sql . "AND P.ing_fechavisacion BETWEEN '" . $ing_fechavisacion . "' AND '" . $ing_fechavisacion_fin . "' ";
            }
            $sql = $sql . "AND P.ing_fechavisacion = '" . $ing_fechavisacion . "' ";
        }
        $i = 0;

        while ($datos = $this->database->fetch_array($result)) {
            $this->arringreso[$i]['prov_id'] = $datos['prov_id'];
            $this->arringreso[$i]['ing_numerodoc'] = $datos['ing_numerodoc'];
            $this->arringreso[$i]['ing_tipodoc'] = $datos['ing_tipodoc'];
            $this->arringreso[$i]['ing_correlativo'] = $datos['ing_correlativo'];
            $this->arringreso[$i]['ing_fechadoc'] = $datos['ing_fechadoc'];
            $this->arringreso[$i]['ing_fechavisacion'] = $datos['ing_fechavisacion'];
            $this->arringreso[$i]['ing_numerovisacion'] = $datos['ing_numerovisacion'];
            $this->arringreso[$i]['ing_moneda'] = $datos['ing_moneda'];
            $this->arringreso[$i]['ing_tipodecambio'] = $datos['ing_tipodecambio'];
            $this->arringreso[$i]['ing_iva'] = $datos['ing_iva'];
            $this->arringreso[$i]['ing_ciftotal'] = $datos['ing_ciftotal'];
            $this->arringreso[$i]['ing_costototal'] = $datos['ing_costototal'];
            $this->arringreso[$i]['ing_viutotal'] = $datos['ing_viutotal'];
            $this->arringreso[$i]['ing_estado_pago'] = $datos['ing_estado_pago'];
            $this->arringreso[$i]['ing_estado_doc'] = $datos['ing_estado_doc'];
            $this->arringreso[$i]['ing_neto'] = $datos['ing_neto'];
            $this->arringreso[$i]['ing_total'] = $datos['ing_total'];
            $this->arringreso[$i]['ing_tipodocsve'] = $datos['ing_tipodocsve'];
            $this->arringreso[$i]['ing_bodega_rec'] = $datos['ing_bodega_rec'];
            $this->arringreso[$i]['oc_id'] = $datos['oc_id'];
            $this->arringreso[$i]['ing_prov_id'] = $datos['ing_prov_id'];
        }
    }

// **********************
// DELETE
// **********************

    function delete() {
        $ing_numerodoc = $this->ing_numerodoc;
        $sql = "DELETE FROM ing_ingreso WHERE ing_numerodoc = $ing_numerodoc;";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {

        $sql = "INSERT INTO ing_ingreso ( prov_id,ing_numerodoc,ing_tipodoc,ing_fechadoc,ing_fechavisacion,ing_numerovisacion,ing_moneda,ing_tipodecambio,ing_iva,ing_ciftotal,ing_costototal,ing_viutotal,ing_estado_pago,ing_estado_doc,ing_neto,ing_total,ing_tipodocsve,ing_bodega_rec ) VALUES ( '$this->prov_id','$this->ing_numerodoc','$this->ing_tipodoc','$this->ing_fechadoc','$this->ing_fechavisacion','$this->ing_numerovisacion','$this->ing_moneda','$this->ing_tipodecambio','$this->ing_iva','$this->ing_ciftotal','$this->ing_costototal','$this->ing_viutotal','$this->ing_estado_pago','$this->ing_estado_doc','$this->ing_neto','$this->ing_total','$this->ing_tipodocsve','$this->ing_bodega_rec' )";
        $result = $this->database->query($sql);
        $this->ing_correlativo = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update($opc) {

        $ing_numerodoc = $this->ing_numerodoc;

        switch ($opc) {
            case 0:
                $sql = " UPDATE ing_ingreso SET  prov_id = '$this->prov_id',ing_numerodoc = '$this->ing_numerodoc',ing_tipodoc = '$this->ing_tipodoc',ing_fechadoc = '$this->ing_fechadoc',ing_fechavisacion = '$this->ing_fechavisacion',ing_numerovisacion = '$this->ing_numerovisacion',ing_moneda = '$this->ing_moneda',ing_tipodecambio = '$this->ing_tipodecambio',ing_iva = '$this->ing_iva',ing_ciftotal = '$this->ing_ciftotal',ing_costototal = '$this->ing_costototal',ing_viutotal = '$this->ing_viutotal',ing_estado_pago = '$this->ing_estado_pago',ing_estado_doc = '$this->ing_estado_doc',ing_neto = '$this->ing_neto',ing_total = '$this->ing_total',ing_tipodocsve = '$this->ing_tipodocsve',ing_bodega_rec = '$this->ing_bodega_rec' WHERE ing_numerodoc = $ing_numerodoc ";
                break;
            case 1:
                $sql = " UPDATE ing_ingreso SET  ing_estado_doc = '$this->ing_estado_doc' WHERE ing_numerodoc = $ing_numerodoc ";
                break;
        }


        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
