
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cls_solicitud_compra
 * GENERATION DATE:  13.04.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cls_solicitud_compra.php
 * FOR MYSQL TABLE:  ing_solicitud_compra
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_solicitud_compra { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $solc_id;   // KEY ATTR. WITH AUTOINCREMENT
    var $solc_fecha;   // (normal Attribute)
    var $solc_fecha_fin;
    var $solc_destino;   // (normal Attribute)
    var $solc_observacion;   // (normal Attribute)
    var $solc_usuario;   // (normal Attribute)
    var $solc_estado;   // (normal Attribute)
    var $solc_tipo;   // (normal Attribute)
    var $database; // Instance of class database
    var $arringsol;

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cls_solicitud_compra() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getsolc_id() {
        return $this->solc_id;
    }

    function getsolc_fecha() {
        return $this->solc_fecha;
    }

    function getsolc_destino() {
        return $this->solc_destino;
    }

    function getsolc_observacion() {
        return $this->solc_observacion;
    }

    function getsolc_usuario() {
        return $this->solc_usuario;
    }

    function getsolc_estado() {
        return $this->solc_estado;
    }

    function getsolc_tipo() {
        return $this->solc_tipo;
    }
    

// **********************
// SETTER METHODS
// **********************


    function setsolc_id($val) {
        $this->solc_id = $val;
    }

    function setsolc_fecha($val) {
        $this->solc_fecha = $val;
    }

    function setsolc_fecha_fin($val) {
        $this->solc_fecha_fin = $val;
    }

    function setsolc_destino($val) {
        $this->solc_destino = $val;
    }

    function setsolc_observacion($val) {
        $this->solc_observacion = $val;
    }

    function setsolc_usuario($val) {
        $this->solc_usuario = $val;
    }

    function setsolc_estado($val) {
        $this->solc_estado = $val;
    }

    function setsolc_tipo($val) {
        $this->solc_tipo = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {

        $solc_id = $this->solc_id;
        $solc_fecha = $this->solc_fecha;
        $solc_fecha_fin = $this->solc_fecha_fin;
        $solc_usuario = $this->solc_usuario;
        $solc_estado = $this->solc_estado;
        $solc_tipo = $this->solc_tipo;

        $sql = "SELECT * FROM ing_solicitud_compra p LEFT JOIN efectua_compra h ON p.solc_id = h.solc_id WHERE ";

        if ($solc_estado != null) {
            $sql = $sql . "P.solc_estado = '" . $solc_estado . "' ";
        } else {
            $sql = $sql . "P.solc_estado > '0' ";
        }
        if ($solc_usuario != null) {
            $sql = $sql . "AND P.solc_usuario = '" . $solc_usuario . "' ";
        }
        if ($solc_id != null) {
            $sql = $sql . "AND P.solc_id = '" . $solc_id . "' ";
        }
        if ($solc_tipo != null) {
            $sql = $sql . "AND P.solc_tipo = '" . $solc_tipo . "' ";
        }
        if ($solc_fecha != null) {
            if ($solc_fecha_fin != null) {
                $sql = $sql . "AND P.solc_fecha BETWEEN '" . $solc_fecha . "' AND '" . $solc_fecha_fin . "' ";
            }
            $sql = $sql . "AND P.solc_fecha = '" . $solc_fecha . "' ";
        }
        $result = $this->database->query($sql);



        $i = 0;
        while ($datos = $this->database->fetch_array($result)) {
            $this->arringsol[$i]['solc_id'] = $datos['solc_id'];
            $this->arringsol[$i]['solc_fecha'] = $datos['solc_fecha'];
            $this->arringsol[$i]['solc_destino'] = $datos['solc_destino'];
            $this->arringsol[$i]['solc_observacion'] = $datos['solc_observacion'];
            $this->arringsol[$i]['solc_usuario'] = $datos['solc_usuario'];
            $this->arringsol[$i]['solc_estado'] = $datos['solc_estado'];
            $this->arringsol[$i]['solc_tipo'] = $datos['solc_tipo'];
            $this->arringsol[$i]['prov_id'] = $datos['prov_id'];
            $this->arringsol[$i]['oc_id'] = $datos['oc_id'];

//            $this->arringsol[$i]['sql'] = $sql;
            $i++;
        }


//        $this->solc_id = $row->solc_id;
//
//        $this->solc_fecha = $row->solc_fecha;
//
//        $this->solc_destino = $row->solc_destino;
//
//        $this->solc_observacion = $row->solc_observacion;
//
//        $this->solc_usuario = $row->solc_usuario;
//
//        $this->solc_estado = $row->solc_estado;
//
//        $this->solc_tipo = $row->solc_tipo;
    }

// **********************
// DELETE
// **********************

    function delete() {
        $solc_id = $this->solc_id;
        $sql = "DELETE FROM ing_solicitud_compra WHERE solc_id = '$solc_id';";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {

        $sql = "INSERT INTO ing_solicitud_compra ( solc_fecha,solc_destino,solc_observacion,solc_estado,solc_tipo )"
                . " VALUES ( '$this->solc_fecha','$this->solc_destino','$this->solc_observacion','$this->solc_estado','$this->solc_tipo' )";
        $result = $this->database->query($sql);


        $this->solc_id = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update($opc) {
        $solc_id = $this->solc_id;

        switch ($opc) {
            case 0:
                $sql = " UPDATE ing_solicitud_compra SET  solc_fecha = '$this->solc_fecha',solc_destino = '$this->solc_destino',"
                        . "solc_observacion = '$this->solc_observacion',solc_tipo = '$this->solc_tipo' WHERE solc_id = '$solc_id' ";
                break;
            case 1:
                $sql = " UPDATE ing_solicitud_compra SET solc_estado = '$this->solc_estado' WHERE solc_id = '$solc_id' ";
                break;
        }
        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
