
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cl_pais
 * GENERATION DATE:  02.05.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cl_pais.php
 * FOR MYSQL TABLE:  pais
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

include_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cl_pais { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $pais_codigo;   // (normal Attribute)
    var $pais_nombre;   // (normal Attribute)
    var $arrpais;
    var $database; // Instance of class database

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cl_pais() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getpais_codigo() {
        return $this->pais_codigo;
    }

    function getpais_nombre() {
        return $this->pais_nombre;
    }

// **********************
// SETTER METHODS
// **********************


    function setpais_codigo($val) {
        $this->pais_codigo = $val;
    }

    function setpais_nombre($val) {
        $this->pais_nombre = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {
        $pais_codigo = $this->pais_codigo;
        $sql = "SELECT * FROM pais WHERE pais_codigo = '$pais_codigo';";
        $result = $this->database->query($sql);
//$result = $this->database->result;
//        $row = mysql_fetch_object($result);
//
//        $this->pais_codigo = $row->pais_codigo;
//        $this->pais_nombre = $row->pais_nombre;
        
        $i=0;
        
        while ($datos = $this->database->fetch_array($result)) {
            $this->arrpais[$i]['pais_codigo'] = $datos['pais_codigo'];
            $this->arrpais[$i]['pais_nombre'] = $datos['pais_nombre'];
        }
    }

// **********************
// DELETE
// **********************

    function delete() {
        $pais_codigo = $this->pais_codigo;
        $sql = "DELETE FROM pais WHERE  pais_codigo = '$pais_codigo'";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {


        $sql = "INSERT INTO pais (pais_nombre ) VALUES ( $this->pais_nombre' )";
        $result = $this->database->query($sql);
        $this->pais_codigo = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update() {

        $pais_codigo = $this->pais_codigo;

        $sql = " UPDATE pais SET  pais_nombre = '$this->pais_nombre' WHERE  pais_codigo = '$pais_codigo'";

        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
