
<!-- begin of generated class -->
<?php
/*
 *
 * -------------------------------------------------------
 * CLASSNAME:        cl_ing_proveedor
 * GENERATION DATE:  02.05.2021
 * CLASS FILE:       C:\xampp\htdocs\generator/generated_classes/class.cl_ing_proveedor.php
 * FOR MYSQL TABLE:  ing_proveedor
 * FOR MYSQL DB:     erpprueba
 * -------------------------------------------------------
 * CODE GENERATED BY:
 * MY PHP-MYSQL-CLASS GENERATOR
 * from: >> www.voegeli.li >> (download for free!)
 * -------------------------------------------------------
 *
 */

require_once("../conexion/conexion.php");

// **********************
// CLASS DECLARATION
// **********************

class cls_ing_proveedor { // class : begin
// **********************
// ATTRIBUTE DECLARATION
// **********************

    var $prov_id;   // KEY ATTR. WITH AUTOINCREMENT
    var $pais_codigo;   // (normal Attribute)
    var $prov_rut;   // (normal Attribute)
    var $prov_rutdig;   // (normal Attribute)
    var $prov_nombre;   // (normal Attribute)
    var $prov_ciudad;   // (normal Attribute)
    var $prov_mail;   // (normal Attribute)
    var $prov_direccion;   // (normal Attribute)
    var $prov_fono;   // (normal Attribute)
    var $prov_contacto;   // (normal Attribute)
    var $prov_servicio;   // (normal Attribute)
    var $prov_condicion_pago;   // (normal Attribute)
    var $prov_ranking;   // (normal Attribute)
    var $prov_giro;   // (normal Attribute)
    var $prov_log;   // (normal Attribute)
    var $arrprov;
    var $database; // Instance of class database

// **********************
// CONSTRUCTOR METHOD
// **********************

    function cls_ing_proveedor() {

        $this->database = new Database();
    }

// **********************
// GETTER METHODS
// **********************


    function getprov_id() {
        return $this->prov_id;
    }

    function getpais_codigo() {
        return $this->pais_codigo;
    }

    function getprov_rut() {
        return $this->prov_rut;
    }

    function getprov_rutdig() {
        return $this->prov_rutdig;
    }

    function getprov_nombre() {
        return $this->prov_nombre;
    }

    function getprov_ciudad() {
        return $this->prov_ciudad;
    }

    function getprov_mail() {
        return $this->prov_mail;
    }

    function getprov_direccion() {
        return $this->prov_direccion;
    }

    function getprov_fono() {
        return $this->prov_fono;
    }

    function getprov_contacto() {
        return $this->prov_contacto;
    }

    function getprov_servicio() {
        return $this->prov_servicio;
    }

    function getprov_condicion_pago() {
        return $this->prov_condicion_pago;
    }

    function getprov_ranking() {
        return $this->prov_ranking;
    }

    function getprov_giro() {
        return $this->prov_giro;
    }

    function getprov_log() {
        return $this->prov_log;
    }

// **********************
// SETTER METHODS
// **********************


    function setprov_id($val) {
        $this->prov_id = $val;
    }

    function setpais_codigo($val) {
        $this->pais_codigo = $val;
    }

    function setprov_rut($val) {
        $this->prov_rut = $val;
    }

    function setprov_rutdig($val) {
        $this->prov_rutdig = $val;
    }

    function setprov_nombre($val) {
        $this->prov_nombre = $val;
    }

    function setprov_ciudad($val) {
        $this->prov_ciudad = $val;
    }

    function setprov_mail($val) {
        $this->prov_mail = $val;
    }

    function setprov_direccion($val) {
        $this->prov_direccion = $val;
    }

    function setprov_fono($val) {
        $this->prov_fono = $val;
    }

    function setprov_contacto($val) {
        $this->prov_contacto = $val;
    }

    function setprov_servicio($val) {
        $this->prov_servicio = $val;
    }

    function setprov_condicion_pago($val) {
        $this->prov_condicion_pago = $val;
    }

    function setprov_ranking($val) {
        $this->prov_ranking = $val;
    }

    function setprov_giro($val) {
        $this->prov_giro = $val;
    }

    function setprov_log($val) {
        $this->prov_log = $val;
    }

// **********************
// SELECT METHOD / LOAD
// **********************

    function select() {
        $prov_id = $this->prov_id;
        $prov_ciudad = $this->prov_ciudad;
        $prov_servicio = $this->prov_servicio;
        $prov_giro = $this->prov_giro;
        
        $sql = "SELECT * FROM ing_proveedor WHERE ";

        if ($prov_id != null) {
            $sql = $sql . "AND prov_id = '" . $prov_id . "' ";
        }
        if ($prov_ciudad != null) {
            $sql = $sql . "AND prov_ciudad = '" . $prov_ciudad . "' ";
        }
        if ($prov_servicio != null) {
            $sql = $sql . "AND prov_servicio = '" . $prov_servicio . "' ";
        }
        if ($prov_giro != null) {
            $sql = $sql . "AND prov_giro = '" . $prov_giro . "' ";
        }

        $result = $this->database->query($sql);

        $i = 0;
        while ($datos = $this->database->fetch_array($result)) {
            $this->arrprov[$i]['prov_id'] = $datos['prov_id'];
            $this->arrprov[$i]['pais_codigo'] = $datos['pais_codigo'];
            $this->arrprov[$i]['prov_rut'] = $datos['prov_rut'];
            $this->arrprov[$i]['prov_rutdig'] = $datos['prov_rutdig'];
            $this->arrprov[$i]['prov_nombre'] = $datos['prov_nombre'];
            $this->arrprov[$i]['prov_ciudad'] = $datos['prov_ciudad'];
            $this->arrprov[$i]['prov_mail'] = $datos['prov_mail'];
            $this->arrprov[$i]['prov_direccion'] = $datos['prov_direccion'];
            $this->arrprov[$i]['prov_fono'] = $datos['prov_fono'];
            $this->arrprov[$i]['prov_contacto'] = $datos['prov_contacto'];
            $this->arrprov[$i]['prov_servicio'] = $datos['prov_servicio'];
            $this->arrprov[$i]['prov_condicion_pago'] = $datos['prov_condicion_pago'];
            $this->arrprov[$i]['prov_ranking'] = $datos['prov_ranking'];
            $this->arrprov[$i]['prov_giro'] = $datos['prov_giro'];
            $this->arrprov[$i]['prov_log'] = $datos['prov_log'];
        }
    }

// **********************
// DELETE
// **********************

    function delete() {
        $prov_id = $this->prov_id;
        $sql = "DELETE FROM ing_proveedor WHERE prov_id = $prov_id;";
        $result = $this->database->query($sql);
    }

// **********************
// INSERT
// **********************

    function insert() {

        $sql = "INSERT INTO ing_proveedor ( pais_codigo,prov_rut,prov_rutdig,prov_nombre,prov_ciudad,prov_mail,prov_direccion,prov_fono,prov_contacto,prov_servicio,prov_condicion_pago,prov_ranking,prov_giro,prov_log ) VALUES ( '$this->pais_codigo','$this->prov_rut','$this->prov_rutdig','$this->prov_nombre','$this->prov_ciudad','$this->prov_mail','$this->prov_direccion','$this->prov_fono','$this->prov_contacto','$this->prov_servicio','$this->prov_condicion_pago','$this->prov_ranking','$this->prov_giro','$this->prov_log' )";
        $result = $this->database->query($sql);
        $this->prov_id = mysql_insert_id();
    }

// **********************
// UPDATE
// **********************

    function update() {
        $prov_id = $this->prov_id;

        $sql = " UPDATE ing_proveedor SET  pais_codigo = '$this->pais_codigo',prov_rut = '$this->prov_rut',prov_rutdig = '$this->prov_rutdig',"
                . "prov_nombre = '$this->prov_nombre',prov_ciudad = '$this->prov_ciudad',prov_mail = '$this->prov_mail',"
                . "prov_direccion = '$this->prov_direccion',prov_fono = '$this->prov_fono',prov_contacto = '$this->prov_contacto',"
                . "prov_servicio = '$this->prov_servicio',prov_condicion_pago = '$this->prov_condicion_pago',prov_ranking = '$this->prov_ranking',"
                . "prov_giro = '$this->prov_giro' WHERE prov_id = $prov_id ";

        $result = $this->database->query($sql);
    }

}

// class : end
?>
<!-- end of generated class -->
